# Site wide configuration

title:            thejunglejane
locale:           en_US
url:              http://thejunglejane.com
# url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: J S Adams
  avatar: IMG_9741.jpg
  bio: "I have data needs. Doing data things to the data at Two Sigma."
  email: jane@thejunglejane.com
  disqus-shortname: 
  twitter: thejunglejane
  facebook: #username
  google:
    plus: #username
    analytics: UA-23556547-3
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: thejunglejane
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: thejunglejane
  xing: #username
  instagram: thejunglejane
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
